### ISSUE TITLE
One drive for Business

### ISSUE THREAD

**Issue by MountainIceMan** [yoichiro/chromeos-filesystem-onedrive#8]
Cant seem to login with a onedrive for business account.

**Comment by yoichiro** [comment]
@MountainIceMan It's a spec. This application allows the OneDrive user only to login to. OneDrive for Business account can't be used, because OneDrive is not same as OneDrive for Business, therefore, API set is not same. This application is using OneDrive API, however, to support the OneDrive for Business, the Office365 API is necessary. Currently, I intend to not support OneDrive for Business account against this application.

**Comment by MountainIceMan** [comment]
Thanks for getting back to me also for the detailed explanation.   Its to
bad you are planning to not developed that feature as I can see a huge user
base that could benefit from it.

**Comment by yoichiro** [comment]
@MountainIceMan Hmm... Sorry for it. If I develop FSP implementation for OneDrive for Business, it will be developed and published as an independent application, not added as the new feature into this application.

**Comment by depstein18** [comment]
How do I change where the mount is pointing to? I think I first tried to link to a one drive business (school) account, but now want to switch to my personal one drive account. I tried re-installing the one drive app but it doesn't prompt me for login info - it just keeps trying to connect to that same one drive business/school account. I'm using a Samsung Chromebook 3.
